name: SLEEP
n_chans: 6
duration: 30

classifier:
  n_classes: 5
  pooling: "last"
  head_type: ${oc.select:head_type,linear}
  mlp_hidden_dim: optuna:categorical:512:256:512
  dropout: optuna:float:0.10:0.05:0.25

data_loader:
  dataset:
    _target_: downstream_tasks.dataloader_course_h5.CourseH5Dataset
    path: ${data_root}/SLEEP
    dataset_name: SLEEP
    ckpt_root: ${ckpt_root}
    normalize: true
    cache_in_memory: false
    resample_to_200hz: false
  batch_size: ${oc.select:batch_size,2}
  seed: ${oc.select:seed,42}
  splits: ["train", "val"]

linear_probing:
  n_epochs: 18
  patience: 5
  warmup_epochs: 0
  mixup: false
  batch_size: ${oc.select:batch_size,2}
  optimizer:
    lr: optuna:float:0.0005:0.0001:0.001:log
    weight_decay: optuna:float:0.0001:1.0e-06:0.01:log
  scheduler:
    patience: 3

mlp_probing:
  n_epochs: 18
  patience: 5
  warmup_epochs: 0
  mixup: false
  batch_size: ${oc.select:batch_size,2}
  optimizer:
    lr: optuna:float:0.0004:0.0001:0.001:log
    weight_decay: optuna:float:0.0001:1.0e-06:0.01:log
  scheduler:
    patience: 3

fine_tuning:
  n_epochs: 10
  patience: 3
  warmup_epochs: 0
  mixup: false
  batch_size: ${oc.select:batch_size,2}
  encoder_lr: optuna:float:2.0e-06:5.0e-07:5.0e-06:log
  head_lr: optuna:float:3.0e-05:1.0e-05:1.0e-04:log
  optimizer:
    lr: 1.0e-04
    weight_decay: optuna:float:0.0001:1.0e-06:0.01:log
  scheduler:
    patience: 2

clip: 100
